id = "vanta-black"
name = "Vanta Black"
version = "0.0.1"
schema_version = 1
authors = ["Mustafa Manhal"]
description = "Vanta Black Bordered them"
repository = "https://github.com/your-name/my-zed-extension"